accent = "#61afef"
active_border_color = "#61afef"
active_tab_background = "#61afef"

cursor = "#e6e6e6"
foreground = "#abb2bf"
background = "#282c34"
selection_foreground = "#e6e6e6"
selection_background = "#61afef"

color0 = "#0e1013"
color1 = "#e06c75"
color2 = "#98c379"
color3 = "#e5c07b"
color4 = "#61afef"
color5 = "#c678dd"
color6 = "#56b6c2"
color7 = "#abb2bf"
color8 = "#5c6370"
color9 = "#e06c75"
color10 = "#98c379"
color11 = "#e5c07b"
color12 = "#61afef"
color13 = "#c678dd"
color14 = "#56b6c2"
color15 = "#e6e6e6"
